export interface RequestItem {
    label: string;
    category: string;
}

const top1000request: RequestItem[] = [
    // Nước chấm & Gia vị (40 items)
    {label: 'Cho thêm nước mắm', category: 'Nước chấm'},
    {label: 'Cho thêm nước tương', category: 'Nước chấm'},
    {label: 'Cho thêm xì dầu', category: 'Nước chấm'},
    {label: 'Cho thêm tương ớt', category: 'Gia vị'},
    {label: 'Cho thêm tương đen', category: 'Gia vị'},
    {label: 'Cho thêm chanh ớt', category: 'Gia vị'},
    {label: 'Cho thêm muối tiêu', category: 'Gia vị'},
    {label: 'Cho thêm ớt xanh', category: 'Gia vị'},
    {label: 'Cho thêm ớt sa tế', category: 'Gia vị'},
    {label: 'Cho thêm mù tạt', category: 'Gia vị'},
    {label: 'Cho thêm tỏi phi', category: 'Gia vị'},
    {label: 'Cho thêm hành phi', category: 'Gia vị'},
    {label: 'Cho thêm mỡ hành', category: 'Gia vị'},
    {label: 'Cho thêm tiêu', category: 'Gia vị'},
    {label: 'Cho thêm dầu mè', category: 'Gia vị'},
    {label: 'Cho thêm sốt mayonnaise', category: 'Nước chấm'},
    {label: 'Cho thêm sốt cà chua', category: 'Nước chấm'},
    {label: 'Cho thêm sốt BBQ', category: 'Nước chấm'},
    {label: 'Cho thêm wasabi', category: 'Gia vị'},
    {label: 'Cho thêm gừng', category: 'Gia vị'},
    {label: 'Cho thêm mắm tôm', category: 'Nước chấm'},
    {label: 'Cho thêm mắm ruốc', category: 'Nước chấm'},
    {label: 'Cho thêm nước cốt chanh', category: 'Nước chấm'},
    {label: 'Cho thêm giấm', category: 'Nước chấm'},
    {label: 'Cho thêm đường', category: 'Gia vị'},
    {label: 'Cho thêm bột ngọt', category: 'Gia vị'},
    {label: 'Cho thêm hạt nêm', category: 'Gia vị'},
    {label: 'Cho thêm mắm nêm', category: 'Nước chấm'},
    {label: 'Cho thêm nước mắm me', category: 'Nước chấm'},
    {label: 'Cho thêm sốt phô mai', category: 'Nước chấm'},
    {label: 'Cho thêm sốt tiêu đen', category: 'Nước chấm'},
    {label: 'Cho thêm sốt bơ tỏi', category: 'Nước chấm'},
    {label: 'Cho thêm nước tương gừng', category: 'Nước chấm'},
    {label: 'Cho thêm tương bần', category: 'Gia vị'},
    {label: 'Cho thêm sốt chanh dây', category: 'Nước chấm'},
    {label: 'Cho thêm sốt thái', category: 'Nước chấm'},
    {label: 'Cho thêm sốt chua ngọt', category: 'Nước chấm'},
    {label: 'Cho thêm mè rang', category: 'Gia vị'},
    {label: 'Cho thêm hạt điều rang', category: 'Gia vị'},
    {label: 'Cho thêm đậu phộng rang', category: 'Gia vị'},

    // Loại bỏ nguyên liệu (50 items)
    {label: 'Không hành', category: 'Loại bỏ'},
    {label: 'Không tỏi', category: 'Loại bỏ'},
    {label: 'Không ớt', category: 'Loại bỏ'},
    {label: 'Không rau mùi', category: 'Loại bỏ'},
    {label: 'Không giá', category: 'Loại bỏ'},
    {label: 'Không ngò', category: 'Loại bỏ'},
    {label: 'Không mùi tây', category: 'Loại bỏ'},
    {label: 'Không chanh', category: 'Loại bỏ'},
    {label: 'Không hành lá', category: 'Loại bỏ'},
    {label: 'Không hẹ', category: 'Loại bỏ'},
    {label: 'Không rau răm', category: 'Loại bỏ'},
    {label: 'Không rau thơm', category: 'Loại bỏ'},
    {label: 'Không tiêu', category: 'Loại bỏ'},
    {label: 'Không gừng', category: 'Loại bỏ'},
    {label: 'Không tía tô', category: 'Loại bỏ'},
    {label: 'Không húng quế', category: 'Loại bỏ'},
    {label: 'Không rau ngót', category: 'Loại bỏ'},
    {label: 'Không rau muống', category: 'Loại bỏ'},
    {label: 'Không rau dền', category: 'Loại bỏ'},
    {label: 'Không hành tây', category: 'Loại bỏ'},
    {label: 'Không ớt hiểm', category: 'Loại bỏ'},
    {label: 'Không gừng sống', category: 'Loại bỏ'},
    {label: 'Không đường', category: 'Loại bỏ'},
    {label: 'Không dầu mỡ', category: 'Loại bỏ'},
    {label: 'Không hạt tiêu', category: 'Loại bỏ'},
    {label: 'Không mè', category: 'Loại bỏ'},
    {label: 'Không lạc', category: 'Loại bỏ'},
    {label: 'Không đậu phộng', category: 'Loại bỏ'},
    {label: 'Không rau sống', category: 'Loại bỏ'},
    {label: 'Không dưa leo', category: 'Loại bỏ'},
    {label: 'Không cà chua', category: 'Loại bỏ'},
    {label: 'Không xà lách', category: 'Loại bỏ'},
    {label: 'Không bắp cải', category: 'Loại bỏ'},
    {label: 'Không cải thảo', category: 'Loại bỏ'},
    {label: 'Không nấm', category: 'Loại bỏ'},
    {label: 'Không đậu que', category: 'Loại bỏ'},
    {label: 'Không bí đao', category: 'Loại bỏ'},
    {label: 'Không bí ngô', category: 'Loại bỏ'},
    {label: 'Không su hào', category: 'Loại bỏ'},
    {label: 'Không củ cải', category: 'Loại bỏ'},
    {label: 'Không khoai tây', category: 'Loại bỏ'},
    {label: 'Không cần tây', category: 'Loại bỏ'},
    {label: 'Không bông cải', category: 'Loại bỏ'},
    {label: 'Không súp lơ', category: 'Loại bỏ'},
    {label: 'Không măng', category: 'Loại bỏ'},
    {label: 'Không rau câu', category: 'Loại bỏ'},
    {label: 'Không cà rốt', category: 'Loại bỏ'},
    {label: 'Không ớt chuông', category: 'Loại bỏ'},
    {label: 'Không hạt sen', category: 'Loại bỏ'},
    {label: 'Không mộc nhĩ', category: 'Loại bỏ'},

    // Độ cay (20 items)
    {label: 'Không cay', category: 'Độ cay'},
    {label: 'Ít cay', category: 'Độ cay'},
    {label: 'Cay nhẹ', category: 'Độ cay'},
    {label: 'Cay vừa', category: 'Độ cay'},
    {label: 'Cay vừa phải', category: 'Độ cay'},
    {label: 'Hơi cay', category: 'Độ cay'},
    {label: 'Khá cay', category: 'Độ cay'},
    {label: 'Rất cay', category: 'Độ cay'},
    {label: 'Cay đặc biệt', category: 'Độ cay'},
    {label: 'Siêu cay', category: 'Độ cay'},
    {label: 'Cay nhiều', category: 'Độ cay'},
    {label: 'Cay nồng', category: 'Độ cay'},
    {label: 'Cay cháy lưỡi', category: 'Độ cay'},
    {label: 'Cay kinh hoàng', category: 'Độ cay'},
    {label: 'Cay tối đa', category: 'Độ cay'},
    {label: 'Cay theo level 1', category: 'Độ cay'},
    {label: 'Cay theo level 2', category: 'Độ cay'},
    {label: 'Cay theo level 3', category: 'Độ cay'},
    {label: 'Cay theo level 4', category: 'Độ cay'},
    {label: 'Cay theo level 5', category: 'Độ cay'},

    // Dầu mỡ (15 items)
    {label: 'Ít dầu', category: 'Dầu mỡ'},
    {label: 'Ít mỡ', category: 'Dầu mỡ'},
    {label: 'Không béo', category: 'Dầu mỡ'},
    {label: 'Ít béo', category: 'Dầu mỡ'},
    {label: 'Bớt dầu', category: 'Dầu mỡ'},
    {label: 'Bớt mỡ', category: 'Dầu mỡ'},
    {label: 'Ăn kiêng', category: 'Dầu mỡ'},
    {label: 'Giảm cân', category: 'Dầu mỡ'},
    {label: 'Ít chất béo', category: 'Dầu mỡ'},
    {label: 'Cắt bỏ mỡ', category: 'Dầu mỡ'},
    {label: 'Bỏ phần mỡ', category: 'Dầu mỡ'},
    {label: 'Không chiên', category: 'Dầu mỡ'},
    {label: 'Không rán', category: 'Dầu mỡ'},
    {label: 'Chế biến không dầu', category: 'Dầu mỡ'},

    // Nhiệt độ (15 items)
    {label: 'Nóng hổi', category: 'Nhiệt độ'},
    {label: 'Ấm nguội', category: 'Nhiệt độ'},
    {label: 'Nóng bỏng tay', category: 'Nhiệt độ'},
    {label: 'Nóng vừa', category: 'Nhiệt độ'},
    {label: 'Ấm áp', category: 'Nhiệt độ'},
    {label: 'Hơi nóng', category: 'Nhiệt độ'},
    {label: 'Mát lạnh', category: 'Nhiệt độ'},
    {label: 'Lạnh', category: 'Nhiệt độ'},
    {label: 'Nhiều đá', category: 'Nhiệt độ'},
    {label: 'Ít đá', category: 'Nhiệt độ'},
    {label: 'Không đá', category: 'Nhiệt độ'},
    {label: 'Đá riêng', category: 'Nhiệt độ'},
    {label: 'Đá viên', category: 'Nhiệt độ'},
    {label: 'Đá bào', category: 'Nhiệt độ'},
    {label: 'Đá nghiền', category: 'Nhiệt độ'},

    // Phần ăn - Thêm nguyên liệu (60 items)
    {label: 'Thêm rau sống', category: 'Phần ăn'},
    {label: 'Thêm thịt', category: 'Phần ăn'},
    {label: 'Thêm đồ tôm', category: 'Phần ăn'},
    {label: 'Thêm trứng', category: 'Phần ăn'},
    {label: 'Thêm bánh phở', category: 'Phần ăn'},
    {label: 'Thêm chanh', category: 'Phần ăn'},
    {label: 'Thêm gà', category: 'Phần ăn'},
    {label: 'Thêm bò', category: 'Phần ăn'},
    {label: 'Thêm heo', category: 'Phần ăn'},
    {label: 'Thêm cơm', category: 'Phần ăn'},
    {label: 'Thêm bún', category: 'Phần ăn'},
    {label: 'Thêm phở', category: 'Phần ăn'},
    {label: 'Thêm miến', category: 'Phần ăn'},
    {label: 'Thêm mì', category: 'Phần ăn'},
    {label: 'Thêm hủ tiếu', category: 'Phần ăn'},
    {label: 'Thêm bánh canh', category: 'Phần ăn'},
    {label: 'Thêm nội tạng', category: 'Phần ăn'},
    {label: 'Thêm chả', category: 'Phần ăn'},
    {label: 'Thêm giò', category: 'Phần ăn'},
    {label: 'Thêm tôm', category: 'Phần ăn'},
    {label: 'Thêm cá', category: 'Phần ăn'},
    {label: 'Thêm mực', category: 'Phần ăn'},
    {label: 'Thêm nghêu', category: 'Phần ăn'},
    {label: 'Thêm sò', category: 'Phần ăn'},
    {label: 'Thêm hến', category: 'Phần ăn'},
    {label: 'Thêm cua', category: 'Phần ăn'},
    {label: 'Thêm ghẹ', category: 'Phần ăn'},
    {label: 'Thêm bạch tuộc', category: 'Phần ăn'},
    {label: 'Thêm sườn', category: 'Phần ăn'},
    {label: 'Thêm xương', category: 'Phần ăn'},
    {label: 'Thêm nạm', category: 'Phần ăn'},
    {label: 'Thêm gân', category: 'Phần ăn'},
    {label: 'Thêm nạc', category: 'Phần ăn'},
    {label: 'Thêm ba chỉ', category: 'Phần ăn'},
    {label: 'Thêm đùi', category: 'Phần ăn'},
    {label: 'Thêm cánh', category: 'Phần ăn'},
    {label: 'Thêm ức', category: 'Phần ăn'},
    {label: 'Thêm tim', category: 'Phần ăn'},
    {label: 'Thêm gan', category: 'Phần ăn'},
    {label: 'Thêm lòng', category: 'Phần ăn'},
    {label: 'Thêm dồi', category: 'Phần ăn'},
    {label: 'Thêm móng giò', category: 'Phần ăn'},
    {label: 'Thêm tai', category: 'Phần ăn'},
    {label: 'Thêm bì', category: 'Phần ăn'},
    {label: 'Thêm xá xíu', category: 'Phần ăn'},
    {label: 'Thêm thịt nguội', category: 'Phần ăn'},
    {label: 'Thêm pate', category: 'Phần ăn'},
    {label: 'Thêm jambon', category: 'Phần ăn'},
    {label: 'Thêm xúc xích', category: 'Phần ăn'},
    {label: 'Thêm trứng gà', category: 'Phần ăn'},
    {label: 'Thêm trứng vịt', category: 'Phần ăn'},
    {label: 'Thêm trứng cút', category: 'Phần ăn'},
    {label: 'Thêm đậu hủ', category: 'Phần ăn'},
    {label: 'Thêm tàu hủ', category: 'Phần ăn'},
    {label: 'Thêm đậu phụ', category: 'Phần ăn'},
    {label: 'Thêm nấm', category: 'Phần ăn'},
    {label: 'Thêm rau củ', category: 'Phần ăn'},
    {label: 'Thêm khoai tây', category: 'Phần ăn'},
    {label: 'Thêm bí đao', category: 'Phần ăn'},
    {label: 'Thêm su hào', category: 'Phần ăn'},

    // Chế biến (40 items)
    {label: 'Tái hơn', category: 'Chế biến'},
    {label: 'Chín kỹ', category: 'Chế biến'},
    {label: 'Giòn tan', category: 'Chế biến'},
    {label: 'Mềm dịu', category: 'Chế biến'},
    {label: 'Chậm món', category: 'Chế biến'},
    {label: 'Yêu cầu làm liền', category: 'Chế biến'},
    {label: 'Rán vàng giòn', category: 'Chế biến'},
    {label: 'Luộc sống', category: 'Chế biến'},
    {label: 'Hấp', category: 'Chế biến'},
    {label: 'Nướng', category: 'Chế biến'},
    {label: 'Chiên', category: 'Chế biến'},
    {label: 'Xào', category: 'Chế biến'},
    {label: 'Rim', category: 'Chế biến'},
    {label: 'Kho', category: 'Chế biến'},
    {label: 'Nấu canh', category: 'Chế biến'},
    {label: 'Nấu súp', category: 'Chế biến'},
    {label: 'Ướp gia vị', category: 'Chế biến'},
    {label: 'Ướp vừa', category: 'Chế biến'},
    {label: 'Ướp đậm đà', category: 'Chế biến'},
    {label: 'Chín vừa', category: 'Chế biến'},
    {label: 'Tái', category: 'Chế biến'},
    {label: 'Medium rare', category: 'Chế biến'},
    {label: 'Medium', category: 'Chế biến'},
    {label: 'Medium well', category: 'Chế biến'},
    {label: 'Well done', category: 'Chế biến'},
    {label: 'Rán giòn', category: 'Chế biến'},
    {label: 'Rán vàng', category: 'Chế biến'},
    {label: 'Chiên giòn', category: 'Chế biến'},
    {label: 'Chiên xù', category: 'Chế biến'},
    {label: 'Nướng than', category: 'Chế biến'},
    {label: 'Nướng lò', category: 'Chế biến'},
    {label: 'Nướng mọi', category: 'Chế biến'},
    {label: 'Nướng giấy bạc', category: 'Chế biến'},
    {label: 'Nướng sơ sơ', category: 'Chế biến'},
    {label: 'Nướng chín kỹ', category: 'Chế biến'},
    {label: 'Làm nhanh', category: 'Chế biến'},
    {label: 'Làm gấp', category: 'Chế biến'},
    {label: 'Ưu tiên', category: 'Chế biến'},
    {label: 'Giao nhanh', category: 'Chế biến'},
    {label: 'Ra liền', category: 'Chế biến'},

    // Vị (30 items)
    {label: 'Ít mặn', category: 'Vị'},
    {label: 'Mặn vừa', category: 'Vị'},
    {label: 'Ít ngọt', category: 'Vị'},
    {label: 'Thêm ngọt', category: 'Vị'},
    {label: 'Ít chua', category: 'Vị'},
    {label: 'Đậm đà', category: 'Vị'},
    {label: 'Nhạt vị', category: 'Vị'},
    {label: 'Không mặn', category: 'Vị'},
    {label: 'Không ngọt', category: 'Vị'},
    {label: 'Không chua', category: 'Vị'},
    {label: 'Thêm chua', category: 'Vị'},
    {label: 'Thêm mặn', category: 'Vị'},
    {label: 'Chua ngọt', category: 'Vị'},
    {label: 'Mặn ngọt', category: 'Vị'},
    {label: 'Vị nhẹ', category: 'Vị'},
    {label: 'Vị đậm', category: 'Vị'},
    {label: 'Đậm đà hơn', category: 'Vị'},
    {label: 'Nhạt hơn', category: 'Vị'},
    {label: 'Vừa miệng', category: 'Vị'},
    {label: 'Không vị', category: 'Vị'},
    {label: 'Ít gia vị', category: 'Vị'},
    {label: 'Nhiều gia vị', category: 'Vị'},
    {label: 'Thơm nồng', category: 'Vị'},
    {label: 'Đậm vị', category: 'Vị'},
    {label: 'Thanh nhẹ', category: 'Vị'},
    {label: 'Đậm vị hơn', category: 'Vị'},
    {label: 'Vị ngọt tự nhiên', category: 'Vị'},
    {label: 'Không bột ngọt', category: 'Vị'},
    {label: 'Không hạt nêm', category: 'Vị'},
    {label: 'Ít hạt nêm', category: 'Vị'},

    // Khác (60 items)
    {label: 'Cắt bỏ phần béo', category: 'Khác'},
    {label: 'Tách riêng phần', category: 'Khác'},
    {label: 'Đánh hộp riêng', category: 'Khác'},
    {label: 'Ra món khác', category: 'Khác'},
    {label: 'Cắt nhỏ', category: 'Khác'},
    {label: 'Cắt mỏng', category: 'Khác'},
    {label: 'Xay nhỏ', category: 'Khác'},
    {label: 'Cắt khúc', category: 'Khác'},
    {label: 'Cắt lát', category: 'Khác'},
    {label: 'Cắt sợi', category: 'Khác'},
    {label: 'Cắt vuông', category: 'Khác'},
    {label: 'Bỏ xương', category: 'Khác'},
    {label: 'Bỏ da', category: 'Khác'},
    {label: 'Bỏ đầu', category: 'Khác'},
    {label: 'Bỏ đuôi', category: 'Khác'},
    {label: 'Gói riêng', category: 'Khác'},
    {label: 'Cho riêng', category: 'Khác'},
    {label: 'Đựng hộp xốp', category: 'Khác'},
    {label: 'Đựng túi nilon', category: 'Khác'},
    {label: 'Không túi nilon', category: 'Khác'},
    {label: 'Cho thêm túi', category: 'Khác'},
    {label: 'Thêm đũa', category: 'Khác'},
    {label: 'Thêm thìa', category: 'Khác'},
    {label: 'Thêm nĩa', category: 'Khác'},
    {label: 'Thêm dao', category: 'Khác'},
    {label: 'Thêm khăn giấy', category: 'Khác'}
]
export default top1000request;
