import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "../styles/globals.css";
import {TableProvider} from "@/hooks/context/Context";
import {ProductProvider} from "@/hooks/context/ContextProduct";
import {FastOrderProvider} from "@/hooks/context/FastOrderContext";
import {DeviceTokenContext, DeviceTokenProvider} from "@/hooks/context/deviceTokenContext";


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export const viewport = {
    width: "device-width",
    initialScale: 1,
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
        <body className="antialiased min-h-screen flex flex-col justify-end items-center bg-white">
        <DeviceTokenProvider>
            <TableProvider>
                <ProductProvider>
                    <FastOrderProvider>
                        {children}
                    </FastOrderProvider>
                </ProductProvider>
            </TableProvider>
        </DeviceTokenProvider>
        </body>
        </html>
    );
}

